# -*- coding: utf-8 -*-
"""train_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MGxAYFNDu-fsGXhHfMjQEfPJWzMOHOGY
"""

import pandas as pd
import numpy as np
import joblib
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_squared_error, r2_score
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from sklearn.impute import SimpleImputer
import optuna
import warnings
warnings.filterwarnings('ignore')

np.random.seed(42)

train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

# Log-transform target for stable training
train['SalePrice_log'] = np.log1p(train['SalePrice'])

# Domain-aware missing value imputation
for col in ['LotFrontage']:
    if col in train.columns:
        train[col] = train.groupby('Neighborhood')[col].transform(lambda x: x.fillna(x.median()))
    if col in test.columns:
        test[col] = test.groupby('Neighborhood')[col].transform(lambda x: x.fillna(x.median()))

none_cols = ['Alley', 'BsmtQual', 'BsmtCond', 'GarageType', 'PoolQC', 'Fence', 'MiscFeature']
for col in none_cols:
    train[col] = train[col].fillna('None')
    test[col] = test[col].fillna('None')

zero_cols = ['MasVnrArea', 'BsmtFinSF1', 'GarageArea', 'TotalBsmtSF']
for col in zero_cols:
    train[col] = train[col].fillna(0)
    test[col] = test[col].fillna(0)

# Fill remaining object columns
for col in train.select_dtypes('object').columns:
    train[col] = train[col].fillna(train[col].mode()[0])
for col in test.select_dtypes('object').columns:
    test[col] = test[col].fillna(test[col].mode()[0])

# Fill remaining numeric columns
for col in train.select_dtypes('number').columns:
    train[col] = train[col].fillna(train[col].median())
for col in test.select_dtypes('number').columns:
    test[col] = test[col].fillna(test[col].median())

print(f"✅ Cleaned: Train {train.shape}, Test {test.shape}")

def add_features(df, is_train=True):
    df = df.copy()
    df['TotalSF'] = df['TotalBsmtSF'] + df['1stFlrSF'] + df['2ndFlrSF']
    df['TotalBath'] = df['FullBath'] + df['HalfBath'] + df['BsmtFullBath'] + df['BsmtHalfBath']
    df['HouseAge'] = 2024 - df['YearBuilt']
    df['IsRemodeled'] = (df['YearRemodAdd'] > df['YearBuilt']).astype(int)
    df['QualArea'] = df['OverallQual'] * df['GrLivArea']

    # Log-transform skewed features
    for col in ['LotFrontage', 'LotArea', '1stFlrSF', 'GrLivArea', 'TotalBsmtSF', 'GarageArea']:
        df[f'{col}_log'] = np.log1p(df[col])

    # Neighborhood encoding (target mean)
    if is_train:
        nb_map = df.groupby('Neighborhood')['SalePrice_log'].mean()
    else:
        # Use training mapping (saved later)
        nb_map = joblib.load("nb_mapping.pkl")
    df['Neighborhood_Encoded'] = df['Neighborhood'].map(nb_map).fillna(nb_map.median())
    return df

train_eng = add_features(train, is_train=True)
joblib.dump(train_eng.groupby('Neighborhood')['SalePrice_log'].mean(), "nb_mapping.pkl")
test_eng = add_features(test, is_train=False)
print("✅ Features engineered")

# Define feature groups (exclude ID, target, redundant)
drop_cols = ['Id', 'SalePrice', 'SalePrice_log']
num_cols = train_eng.select_dtypes('number').drop(columns=drop_cols).columns
cat_cols = train_eng.select_dtypes('object').columns

preprocessor = ColumnTransformer(
    transformers=[
        ('num', Pipeline([('imputer', SimpleImputer(strategy='median')),
                          ('scaler', StandardScaler())]), num_cols),
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), cat_cols)
    ],
    remainder='drop'
)

X = train_eng.drop(columns=drop_cols)
y = train_eng['SalePrice_log']
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

X_train_p = preprocessor.fit_transform(X_train)
X_val_p = preprocessor.transform(X_val)

# Quick model comparison
models = {
    'XGBoost': XGBRegressor(n_estimators=200, learning_rate=0.05, random_state=42),
    'LightGBM': LGBMRegressor(n_estimators=200, learning_rate=0.05, random_state=42)
}

for name, model in models.items():
    model.fit(X_train_p, y_train)
    pred = model.predict(X_val_p)
    rmse = np.sqrt(mean_squared_error(y_val, pred))
    print(f"{name}: RMSE(log)={rmse:.4f} | RMSE($)=${np.sqrt(mean_squared_error(np.expm1(y_val), np.expm1(pred))):,.0f}")

def objective(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 100, 500),
        'max_depth': trial.suggest_int('max_depth', 3, 9),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.2, log=True),
        'subsample': trial.suggest_float('subsample', 0.7, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.7, 1.0),
        'reg_alpha': trial.suggest_float('reg_alpha', 1e-3, 10, log=True),
        'random_state': 42
    }
    model = XGBRegressor(**params)
    scores = cross_val_score(model, X_train_p, y_train, cv=5, scoring='neg_root_mean_squared_error')
    return -scores.mean()

study = optuna.create_study(direction='minimize')
study.optimize(objective, n_trials=30, show_progress_bar=True)
print(f"✅ Best RMSE: {-study.best_value:.4f}")

# Train final model
best_model = XGBRegressor(**study.best_params)
best_model.fit(X_train_p, y_train)

# Save for Streamlit
joblib.dump(best_model, "house_price_model.pkl")
joblib.dump(preprocessor, "house_price_preprocessor.pkl")
joblib.dump(preprocessor.get_feature_names_out(), "feature_names.pkl")
print("✅ Model & artifacts saved!")